# Generated by Django 5.0.2 on 2024-02-18 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('sur_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество')),
                ('start_study', models.DateField(blank=True, null=True, verbose_name='Дата поступления в школу')),
                ('end_study', models.DateField(blank=True, null=True, verbose_name='Дата поступления в школу')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='В случае ухода/перехода из школы - причина')),
                ('hearing', models.SmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], null=True, verbose_name='Слух')),
                ('rhythm', models.SmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], null=True, verbose_name='Ритм')),
                ('memory', models.SmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], null=True, verbose_name='Память')),
                ('musical_training', models.SmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], null=True, verbose_name='Музыкальная подготовка')),
                ('home_address', models.TextField(blank=True, null=True, verbose_name='Домашний адресс')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='телефон')),
                ('place_of_study', models.TextField(blank=True, null=True, verbose_name='Место учёбы')),
                ('mother', models.CharField(blank=True, max_length=256, null=True, verbose_name='Мать')),
                ('mother_phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Телефон матери')),
                ('mother_work_place', models.TextField(blank=True, null=True, verbose_name='Место работы/должность матери')),
                ('father', models.CharField(blank=True, max_length=256, null=True, verbose_name='Отец')),
                ('father_phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Телефон отца')),
                ('father_work_place', models.TextField(blank=True, null=True, verbose_name='Место работы/должность отца')),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.workplace')),
            ],
        ),
    ]
