# Generated by Django 5.0.2 on 2024-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workplace',
            constraint=models.UniqueConstraint(fields=('school', 'user'), name='Уникальная связь Учитель - школа.'),
        ),
    ]
