# Generated by Django 5.0.2 on 2024-04-07 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workplace_уникальная_связь_учитель_школа_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
