# Generated by Django 5.0.2 on 2024-04-13 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_workplace_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hearing',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Слух'),
        ),
        migrations.AlterField(
            model_name='student',
            name='memory',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='student',
            name='musical_training',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Музыкальная подготовка'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rhythm',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Ритм'),
        ),
        migrations.AlterField(
            model_name='student',
            name='work_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.workplace', verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school', verbose_name='Учебное заведение'),
        ),
    ]
