# Generated by Django 5.0.2 on 2024-04-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_hearing_alter_student_memory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='Подпись'),
        ),
    ]
