# Generated by Django 5.0.2 on 2024-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teacher_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
