# Generated by Django 5.0.2 on 2024-04-30 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('users', '0006_alter_teacher_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='id',
        ),
        migrations.AlterField(
            model_name='plan',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='plans', serialize=False, to='users.student', verbose_name='Студент'),
        ),
    ]
